hydra:
  run:
    dir: ./output/${now:%Y-%m-%d}/${now:%H-%M-%S}/emag_epic

main:
  monitored_metric: "val_loss"
  seed: 42
  train: True
  test: False
  accelerator: gpu
  devices: [0, 1]
  strategy: dp
  ckpt_pth: 
  resume_ckpt:

model_config:
  backbone:
    base: resnet18
    pretrained: True

  # Model
  transformer:
    src_in_features_hoi: 512
    trg_in_features_hoi: 512
    src_in_features_ego: 9
    trg_in_features_ego: 512
    use_flow: True
    num_patches_hoi: 4
    num_patches_ego: 1
    num_patches_global: 2

    embed_dim_hoi: 512
    embed_dim_ego: 512
    num_heads: 8
    enc_depth: 2
    dec_depth: 2

    coord_dim: 64
    hidden_dim: 512
    latent_dim: 256

    encoder_time_embed_type: sin # sin, param
    decoder_time_embed_type: sin # sin, param

    num_frames_input_hoi: 8
    num_frames_output_hoi: 4
    num_frames_input_ego: 8
    num_frames_output_ego: 4

  # OPTIMIZER
  optimizer:
    optimizer: adamw # adam, rms, sdg, adamw
    scheduler: cosine # step, multistep, cosine
    lr: 2e-4
    weight_decay: 1e-3
    momentum: 0.9
    lr_decay_step: 10
    lr_decay_gamma: 0.5
    max_epochs: 30
    warmup_epochs: 5
    warmup_lr_init: 0

data_module:
  train_type: train
  test_type: val
  num_frames_hoi: 8
  num_frames_ego: 8
  num_pred_ego: 4

  # epic
  data_dir: /data/EPIC-KITCHENS-55
  pickle: /data/EPIC-KITCHENS-55/hand-objects
  interval: 16
  interval_ego_input: 16
  interval_ego_output: 16
  mean_rgb: [0.3025, 0.3258, 0.3849]
  std_rgb: [0.2385, 0.2388, 0.2423] 
  mean_flow: [0.0799, 1.2739, 0] 
  std_flow: [14.5276, 8.4646, 1] 
  # homography
  mean_ego: [ 9.9695e-01,  7.4786e-03, -1.1576e+00, 
              9.0954e-04,  9.9841e-01,  6.2787e-01, 
             -7.6744e-06, -1.1019e-06,  1.0000e+00]
  std_ego: [7.6549e-02, 5.3323e-02, 1.8628e+01, 
            2.6139e-02, 8.4444e-02, 1.0856e+01,
            1.3653e-04, 2.2441e-04, 1]

  batch_size: 60  # 60
  num_workers: 9  # 9
  delete: []
