hydra:
  run:
    dir: ./output/${now:%Y-%m-%d}/${now:%H-%M-%S}/emag_ego4d

main:
  monitored_metric: "val_loss"
  seed: 42
  train: False
  test: True
  accelerator: gpu
  devices: [0, 1] #[0, 1, 2, 3, 4, 5, 6, 7]
  strategy: dp
  ckpt_pth: 
  resume_ckpt:

model_config:
  backbone:
    base: resnet18 # resnet18, resnet34, resnet50, resnet101, resnet152
    pretrained: True

  # Model
  transformer:
    src_in_features_hoi: 512
    trg_in_features_hoi: 512
    src_in_features_ego: 9
    trg_in_features_ego: 512
    use_flow: True
    num_patches_hoi: 4
    num_patches_ego: 1
    num_patches_global: 2

    embed_dim_hoi: 512
    embed_dim_ego: 512
    num_heads: 8
    enc_depth: 2
    dec_depth: 2

    coord_dim: 64
    hidden_dim: 512
    latent_dim: 256

    encoder_time_embed_type: sin # sin, param
    decoder_time_embed_type: sin # sin, param

    num_frames_input_hoi: 8
    num_frames_output_hoi: 4
    num_frames_input_ego: 8
    num_frames_output_ego: 4

  # OPTIMIZER
  optimizer:
    optimizer: adamw # adam, rms, sdg, adamw
    scheduler: cosine # step, multistep, cosine
    lr: 2e-4
    weight_decay: 1e-3
    momentum: 0.9
    lr_decay_step: 10
    lr_decay_gamma: 0.5
    max_epochs: 30
    warmup_epochs: 5
    warmup_lr_init: 0

data_module:
  train_type: train
  test_type: val
  num_frames_hoi: 8
  num_frames_ego: 8
  num_pred_ego: 4

  # ego4d
  data_dir: /data/ego4d_data/v1
  pickle: /data/ego4d_data/v1/hand-objects
  interval: 8
  interval_ego_input: 8
  interval_ego_output: 8
  mean_rgb: [0.3325, 0.3664, 0.4069]
  std_rgb: [0.2248, 0.2266, 0.2451] 
  mean_flow: [-0.0091, 0.4864, 0]
  std_flow: [10.8595, 9.1097, 1]
  # homography
  mean_ego: [1.0002e+00,  4.0572e-03, -9.2904e-01,  
             2.4077e-03,  1.0002e+00, -2.2682e-01, 
             2.2475e-06,  4.3294e-06,  1.0000e+00] 
  std_ego: [7.1561e-02, 4.3756e-02, 1.4797e+01, 
             3.3578e-02, 8.3743e-02, 1.1440e+01,
             1.5850e-04, 1.8914e-04, 1]

  batch_size: 60  # 60
  num_workers: 9  # 9
  delete: [
    "d18ef16d-f803-4387-bb5e-7876f1522a63",
    "77ed1624-f87b-4196-9a0a-95b7023b18e4",
    "128f69dd-f61d-494f-84c2-f3a8c937ae8f",
    "09910d48-41f9-4a84-bb1b-1bc96de62286",
    "8e914832-2dd1-44fd-81f8-1b7e2ccd2402",
  ]              
